name: CI voor Kassasysteem Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Haal de code op
        uses: actions/checkout@v3

      - name: Installeer Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven build en tests
        run: mvn clean verify
