#name: CI voor Kassasysteem Backend
#
#on:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]
#
#jobs:
#  build-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Haal de code op
#        uses: actions/checkout@v3
#
#      - name: Installeer Java 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Maven build en tests
#        run: mvn clean verify


name: CI/CD Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Haal de code op
        uses: actions/checkout@v3

      - name: Installeer Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & test met Maven
        run: mvn clean verify

      - name: Log in bij Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Bouw en push image naar Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kassa-backend:latest
